// TUTORIALS REST CLIENT 

// Create a new Tutorial
###
post http://localhost:8080/api/tutorials
Content-Type: application/json


{
    "id": 1,
    "title": "JS: Node Tut #1",
    "description": "Tut#1 Description",
    "published": false,
    "updatedAt": "2019-12-13T01:13:57.650Z",
    "createdAt": "2019-12-13T01:13:57.650Z"
}


# Get All Tutorials
###
get http://localhost:8080/api/tutorials

# Get single Tutorial
###
get http://localhost:8080/api/tutorials/2

# Update a Tutorial
###
put http://localhost:8080/api/tutorials/2
Content-Type: application/json

{
    "published": true
}


# Find all Tutorials which title contains ‘node’
###
get http://localhost:8080/api/tutorials?title=node

# Find all published tutorials
###
get http://localhost:8080/api/tutorials/published


# Delete a tutorial
###
delete http://localhost:8080/api/tutorials/1


# Delete ALL tutorial
###
delete http://localhost:8080/api/tutorials/

